services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  backend:
    image: python:3.9
    working_dir: /app
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    ports:
      - "8000:8000"
    dns:
      - 223.5.5.5  # 阿里云DNS
      - 223.6.6.6  # 阿里云DNS备用
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
    command: >
      sh -c "
        cd backend &&
        pip install -r requirements.txt &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      " 